twig:
    default_path: '%kernel.project_dir%/templates'

    # activation du thème bootstrap 5 pour les formulaire
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
